server:
  port: 80

spring:
  application:
    name: cloud-consumer-order
  cloud:
    consul:
      host: 192.168.1.174
      port: 8500
      discovery:
        service-name: ${spring.application.name}
        #打开心跳
        heartbeat:
          enabled: true
