server:
  port: 9002
spring:
  application:
    name: nacos-payment-provider
  cloud:
    nacos:
      discovery:
        server-addr: 192.168.1.217:8848 #注册地址
#暴露监控端口
management:
  endpoints:
    web:
      exposure:
        include: '*'