server:
  port: 8801

spring:
  application:
    name: cloud-stream-provider
  cloud:
    stream:
      binders: #配置绑定的rabbitmq的服务信息
        defaultRabbit: #定义的名称
          type: rabbit #消息组件类型
          environment:
            spring:
              rabbitmq:
                host: 192.168.1.217
                prot: 5672
                username: admin
                password: admin
      bindings: #服务整合处理
        output: #通道名称
          destination: lxpExchange #交换机名称
          content-type: application/json #设置消息类型，文本则设置“text/plain”
          binder: defaultRabbit #设置要绑定的消息服务的具体设置
eureka:
  client:
    service-url:
      defaultZone: http://localhost:7001/eureka
  instance:
    lease-renewal-interval-in-seconds: 2 #设置心跳的时间间隔
    lease-expiration-duration-in-seconds: 5 #间隔时间
    instance-id: send-8801.com #在信息列表时显示的主机名称
    prefer-ip-address: true #访问的路径变为IP地址
