server:
  port: 8001

spring:
  application:
    name: cloud-payment-server
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    url: jdbc:mysql://192.168.1.174:3306/db2021?useUnicode=true&characterEncoding=utf-8&useSSL=false
    username: root
    password: root
  driver-class-name: org.gjt.mm.mysql.Driver


mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.lxp.springcloud.entities

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka/,http://eureka7002.com:7002/eureka/
  instance:
    instance-id: payment8001
    #显示IP地址
    prefer-ip-address: true
    #Eureka客户端向服务端发送心跳的时间间隔，单位为秒（默认30秒）
    lease-renewal-interval-in-seconds: 1
    #Eureka服务端在收到最后一次心跳后等待的时间上限（默认90秒），超时将剔除服务
    lease-expiration-duration-in-seconds: 2