server:
  port: 8002

spring:
  application:
    name: cloud-payment-server
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    url: jdbc:mysql://192.168.1.174:3306/db2021?useUnicode=true&characterEncoding=utf-8&useSSL=false
    username: root
    password: root
  driver-class-name: org.gjt.mm.mysql.Driver


mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.lxp.springcloud.entities

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka/,http://eureka7002.com:7002/eureka/
  instance:
    #配置instance-id之后，在eureka中就会看到
    instance-id: payment8002
    #显示IP地址
    prefer-ip-address: true