server:
  port: 9527

spring:
  application:
    name: cloud-gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true #开启从服务注册中心动态创建路由的功能，使用微服务名称进行路由
      #路由配置
      routes:
        - id: payment_routh #路由的ID，没有固定规则但要求唯一，建议配合服务名
          #uri: http://localhost:8001 #匹配后提供服务的路由地址
          uri: lb://CLOUD-PAYMENT-SERVER #负载均衡，微服务名称构成路由地址
          predicates:
#            - After=2021-04-21T11:31:13.638801600+08:00[Asia/Shanghai]
#            - Before=2022-04-21T11:31:13.638801600+08:00[Asia/Shanghai]
#            - Between=2021-04-21T11:31:13.638801600+08:00[Asia/Shanghai], 2022-04-21T11:31:13.638801600+08:00[Asia/Shanghai]
#            #在Cookie中需要有一个key是username，值是lxp的信息
#            - Cookie=username, lxp
#            #在请求头（Header）中需要一个key是X-Request-Id，值是整数的信息
#            - Header=X-Request-Id, \d+
#            #在请求头的Host中需要匹配的规则,配置多个则符合任意一个即可
#            - Host=**.lxp.com, **.tt.com
#            #提交请求的方式
#            - Method=GET
#            #路径匹配
            - Path=/payment/get/** #断言，路径相匹配的进行路由
#            #查询参数，如果是一个则表示有就可以，如果是两个，则表示不仅要有，参数的值也必须符合正则
#            - Query=uuu, \d+
        - id: payment_routh2
          #uri: http://localhost:8001
          uri: lb://CLOUD-PAYMENT-SERVER
          predicates:
            - Path=/payment/timeout/**
eureka:
  instance:
    hostname: cloud-gateway-service
  client:
    service-url:
      register-with-eureka: true
      fetch-registry: true
      defaultZone: http://eureka7001.com:7001/eureka