server:
  port: 2001

spring:
  application:
    name: seata-order-service
  cloud:
    alibaba:
      seata:
        tx-service-group: default
    nacos:
      discovery:
        server-addr: 192.168.1.217:8848
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://192.168.1.174:3306/seata_order
    username: root
    password: root
logging:
  level:
    io:
      seata: info
mybatis:
  mapperLocations: classpath:mapper/*.sml

#seata配置
seata:
  enabled: true
  enable-auto-data-source-proxy: true
  tx-service-group: my_test_tx_group
  registry: #注册
    type: nacos
    nacos:
      application: seata-server # seata在nacos中的服务名称
      server-addr: 192.168.1.217:8848 # nacos地址
#      namespace: 2275314e-9569-47f8-b4f7-65317cdf3025 # 命名空间ID
  config: #配置信息
    type: nacos
    nacos:
      server-addr: 192.168.1.217:8848 # nacos服务地址
      group: SEATA_GROUP
#      username: nacos
#      password: nacos
#      namespace: 2275314e-9569-47f8-b4f7-65317cdf3025 # 命名空间ID
  service:
    vgroup-mapping:
      my_test_tx_group: default
    disable-global-transaction: false
  client:
    rm:
      report-success-enable: false